apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hasura
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hasura
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hasura
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hasura
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v1.1.0
        name: hasura
        ports:
        - containerPort: 8080
        resources: {}
status: {}
