apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: hasura
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: hasura
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hasura
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hasura
  strategy: {}
  env:
    - name: PORT
      value: "${PORT}"
    - name: HASURA_GRAPHQL_DATABASE_URL
      value: "${HASURA_GRAPHQL_DATABASE_URL}"
    - name: HASURA_GRAPHQL_ADMIN_SECRET
      value: "${HASURA_GRAPHQL_ADMIN_SECRET}"
    - name: HASURA_GRAPHQL_ENABLE_CONSOLE
      value: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
    - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
      value: "${HASURA_GRAPHQL_ENABLED_LOG_TYPES}"
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hasura
    spec:
      containers:
      - image: hasura/graphql-engine:v1.1.0
        name: hasura
        ports:
        - containerPort: 8080
        resources: {}
status: {}
