---
# include:
#   - project: SocialGouv/gitlab-ci-yml
#     file: /autodevops_simple_app.yml
#     ref: v7.3.3
#
# variables:
#   PROJECT: "hasura"
#   PORT: 8080
#   VALUES_FILE: ./.k8s/app.values.yml



image: hasura/graphql-engine:v1.1.0

# stages:
#   - build
#   - deploy
#
# build:
#   stage: build
#   # script: ./mvnw package
#   # artifacts:
#   #   paths:
#   #     - target/demo-0.0.1-SNAPSHOT.jar
#
# production:
#   stage: deploy
#   script:
#     - curl --location "https://cli.run.pivotal.io/stable?release=linux64-binary&source=github" | tar zx
#     - ./cf login -u $CF_USERNAME -p $CF_PASSWORD -a api.run.pivotal.io
#     - ./cf push
#   only:
#     - master
