---
# include:
#   - project: SocialGouv/gitlab-ci-yml
#     file: /autodevops_simple_app.yml
#     ref: v7.3.3
#
# variables:
#   PROJECT: "hasura"
#   PORT: 8080
#   VALUES_FILE: ./.k8s/app.values.yml

before_script:
  - docker info

build_image:
  script:
    - docker build -t hasura .
    - docker run hasura
